image: docker:24.0

services:
  - docker:24.0-dind

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: $CI_REGISTRY_IMAGE/botpress-nlu-ptbr:$CI_COMMIT_REF_NAME
  DOCKER_TLS_CERTDIR: ""

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

workflow:
  rules:
    - if: '$CI_COMMIT_TAG =~ /NLU/'

stages:
  - build_and_push

build_and_push_image:
  stage: build_and_push
  script:
    - docker build -t $IMAGE_NAME ./nlu
    - docker push $IMAGE_NAME
  only:
    - tags
