image: docker:24.0

services:
  - docker:24.0-dind

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: $CI_REGISTRY_IMAGE/botpress-nlu-ptbr:$CI_COMMIT_REF_NAME
  DOCKER_TLS_CERTDIR: ""

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

workflow:
  rules:
    # A pipeline será executada apenas se a tag do commit seguir o padrão "NLU"
    - if: '$CI_COMMIT_TAG =~ /NLU/'

stages:
  - build
  - push

build_image:
  stage: build
  script:
    # Construindo a imagem Docker com o nome baseado no commit/tag
    - docker build -t $IMAGE_NAME ./nlu
  only:
    # A pipeline só rodará em commits que possuem tags
    - tags

push_image:
  stage: push
  needs: ["build_image"]
  script:
    # Após a imagem ser construída, ela será enviada para o GitLab Registry
    - docker push $IMAGE_NAME
  only:
    # O push da imagem será realizado apenas em commits com tags
    - tags
