services:
  botpress:
    user: "0" # root precisamos ver uma solução para esse problema
    command: bash -c "./duckling & ./bp"
    image: chatbotbp/botpress_brasil_participativo:v1_0_1
    container_name: botpress
    ports:
      - "3000:3000"
    environment:
      BP_MODULE_NLU_DUCKLINGURL: "http://nlu_portugues:8000"
      BP_MODULE_NLU_LANGUAGESOURCES: '[{"endpoint":"http://nlu_portugues:3100"}]'
      BOTPRESS_ADMIN_EMAIL: ${BOTPRESS_ADMIN_EMAIL}
      BOTPRESS_ADMIN_PASSWORD: ${BOTPRESS_ADMIN_PASSWORD}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@{POSTGRES_HOST}:5432/${POSTGRES_DB}

      BP_PRODUCTION: true
    depends_on:
      - nlu_portugues
    volumes:
      - ./data:/botpress/data
      - ./data/assets:/botpress/assets 
    networks:
      - botpress-network

  nlu_portugues:
    image: gxaite/nlu_portugues:latest
    container_name: nlu_portugues
    ports:
      - "3100:3100"
      - "8000:8000"
    command: bash -c "./duckling -p 8000 & ./bp lang --offline --dim 100 --langDir /botpress/NLU --port 3100"
    networks:
      - botpress-network

volumes:
  botpress_data:

networks:
  botpress-network:
    driver: bridge
