apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s-deployment/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    app: botpress-brasil-participativo
  name: botpress-brasil-participativo
spec:
  type: NodePort
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    app: botpress-brasil-participativo
